sudo: required
services:
  - docker

before_install:
  - docker build -t karthikgirraj/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run karthikgirraj/multi-docker-test npm run test -- --coverage

after_success:
  - docker build -t karthikgirraj/multi-client ./client
  - docker build -t karthikgirraj/multi-nginx ./nginx
  - docker build -t karthikgirraj/multi-server ./server
  - docker build -t karthikgirraj/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push karthikgirraj/multi-client
  - docker push karthikgirraj/multi-nginx
  - docker push karthikgirraj/multi-server
  - docker push karthikgirraj/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-577683050298"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"